[theme]
primaryColor = "#FFFFFF" # Cor principal do tema.
backgroundColor = "#FFFFFF" #Cor de fundo da aplicação.
secondaryBackgroundColor = "#FFFFFF" # Cor de fundo secundária, usada em elementos como a tabela.
textColor = "#FFFFFF"
font = "sans serif"
